spring:
  application:
    name: salon-main-api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/salon?autoReconnect=true&characterEncoding=UTF-8
    username: salon
    password: salon12345!

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jwt:
    expiration_time: 3600000 # 1시간
    secret: OjgofgAtCDjBpf5Cp0j5fFtbfQ85BSuQhSnXpMKQjcNw9VFr

  data:
    redis:
      host: localhost
      port: 6379
      password:

server:
  port: 1180

logging:
  level:
    root: error
    com.project.salon.main.api: info
    org.hibernate.resource: info
    com.zaxxer.hikari.pool.HikariPool: debug
    com.zaxxer.hikari: trace